using UnityEngine;

namespace ADPlatform.TestField
{
    /// <summary>
    /// Proxy that inherits WaypointManager to satisfy E2EDrivingAgent's dependency
    /// while providing grid-specific intersection/speed info.
    /// Updated per-frame by TestFieldManager based on each agent's position.
    /// </summary>
    public class GridWaypointProxy : ADPlatform.Agents.WaypointManager
    {
        [Header("Grid Reference")]
        public GridRoadNetwork gridNetwork;

        // Per-agent state updated externally by TestFieldManager
        [HideInInspector] public int agentRouteIndex;
        [HideInInspector] public int currentRouteWaypointIdx;

        private GridRouteDefinition assignedRoute;

        /// <summary>
        /// Initialize proxy for a specific agent route.
        /// Sets up base WaypointManager fields that E2EDrivingAgent reads.
        /// </summary>
        public void InitializeForRoute(GridRouteDefinition route, int routeIdx)
        {
            assignedRoute = route;
            agentRouteIndex = routeIdx;

            // Override base class fields
            intersectionType = 2;    // Always Cross (grid)
            numLanes = 3;
            laneWidth = 3.5f;
            centerLineEnabled = false;
            defaultSpeedLimit = 16.67f;  // 60 km/h
            roadCurvature = 0f;

            // Disable base class behaviors
            enableRealtimeUpdate = false;
        }

        /// <summary>
        /// Update intersection info based on agent's current position and forward direction.
        /// Called by TestFieldManager every frame for each agent.
        /// Uses position-based search to find the next intersection ahead (P-030).
        /// </summary>
        public void UpdateForAgent(Vector3 agentPos, Vector3 agentForward, int routeWpIdx)
        {
            currentRouteWaypointIdx = routeWpIdx;
            if (gridNetwork == null || assignedRoute == null) return;

            float bestDist = float.MaxValue;
            int bestIdx = -1;

            for (int i = 0; i < assignedRoute.waypoints.Length; i++)
            {
                Vector2Int wp = assignedRoute.waypoints[i];
                Vector3 iPos = gridNetwork.GetIntersectionPosition(wp.x, wp.y);
                Vector3 toIntersection = iPos - agentPos;
                float dist = toIntersection.magnitude;

                if (dist < 5f) continue;              // Already at/past this intersection
                float dot = Vector3.Dot(toIntersection.normalized, agentForward);
                if (dot < 0.2f) continue;             // Behind or perpendicular

                if (dist < bestDist)
                {
                    bestDist = dist;
                    bestIdx = i;
                }
            }

            if (bestIdx >= 0)
            {
                intersectionDistance = bestDist;
                turnDirection = bestIdx < assignedRoute.turnTypes.Length
                    ? assignedRoute.turnTypes[bestIdx] : 0;
            }
            else
            {
                intersectionDistance = 200f;
                turnDirection = 0;
            }
        }

        // Override base methods for grid behavior

        public new float GetCurrentSpeedLimit(Vector3 worldPosition)
        {
            return defaultSpeedLimit;
        }

        public new float GetNextSpeedLimit(Vector3 worldPosition)
        {
            return defaultSpeedLimit;
        }

        public new bool IsWrongWayDriving(float xPos, float zPos)
        {
            return false;  // Disabled in grid (multiple directions)
        }

        public new bool IsWrongWayDriving(float xPos)
        {
            return false;
        }

        /// <summary>
        /// Prevent base class Start() from generating linear waypoints.
        /// </summary>
        private void Awake()
        {
            // Override: don't call base Start/GenerateWaypoints
            enableRealtimeUpdate = false;
        }

        private new void Start()
        {
            // Intentionally empty - grid waypoints are generated by GridRoadNetwork
        }
    }
}
